spring:

  datasource:
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      jdbc-url: ${DB_URL}
      maximum-pool-size: 5
      minimum-idle: 3

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      format-sql: true

server:
  port: 8081
