spring:

  datasource:
    url: jdbc:mysql://172.20.0.2/alga_food?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: alga
    password: toor

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      format-sql: true

server:
  port: 8081
